site_name: LHL Research Docs
repo_url: https://github.com/jaykhan-lhl/lhl-docs
repo_name: jaykhan-lhl/lhl-docs
theme:
  name: material
  font:
    text: Lato

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.tabs

  palette:
   

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

      primary: amber
      accent: blue

plugins:
  - tags:
      tags_file: tags.md
  - search

markdown_extensions:
  - meta
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:

  - Web:
      - WordPress: 
        - Accessibility: web/wordpress/accessibility.md
        - Microsites: web/wordpress/microsites.md
        - Oxygen: web/wordpress/oxygen.md
        - REST API: web/wordpress/rest-api.md
      - Vue JS:
        - WordPress + Vue: web/vue/wordpress-connect.md
        - Authentication: web/vue/vue-auth.md
        - Accessibility: web/vue/accessibility.md
      - RoR:
        - Blog: web/ror/blog.md
        - Deployment: web/ror/deployment.md

  - Graphics:
      - Assets: 
        - Overview: graphics/assets/overview.md
      - Stylesheets: graphics/stylesheets/stylesheets.md
      